### ISSUE TITLE
Dioide Polarity??

### ISSUE THREAD

**Issue by Alexcoleman268** [barnabywalters/Schraeg#3]
What is the polarity of the diodes on D1 and D2? Theres no mark on the PCB and i cant find any pictures??

**Comment by barnabywalters** [comment]
The polarity is indicated on the silkscreen, but KiCAD’s method for doing so is, uh, “minimal” (same for ICs — in the future I will try to use better silkscreen graphics). Here’s a photo showing correct orientations of the diodes:

![IMG_6709](https://user-images.githubusercontent.com/968350/150598988-fdd64361-27e7-488a-b49f-3168b772dc51.jpeg)

**Comment by Alexcoleman268** [comment]
Thanks! I ended up checking some post on Lines and figured it out, I built my module though and sadly its not working, All my soldering is great I have a ton of SMD experience, Is there anything on the V 2.0 boards from pusherman I need to do differently than just build as is? I know there were some problems with a couple of the boards.

Thanks a ton!
Alex

**Comment by barnabywalters** [comment]
Sorry to hear its not working! If you have a v0.2.0 board I can think of two known issues.

The old layout only worked as-is with certain LM4040s, but can be fixed by soldering the LM4040s at a funny angle so that the correct pins meet the correct pads:

https://github.com/barnabywalters/Schraeg#v02
https://github.com/barnabywalters/Schraeg/issues/2

Also, apparently I got the rectifier symbol mixed up, which could lead to the module only getting powered with the power connector in one of the two possible orientations, as described here: https://llllllll.co/t/diy-module-release-schrag-bastl-cinnamon-rework/40590/23

If neither of those fix things, best thing to do would be to debug it as far as you can get by yourself (e.g. checking voltage supply rails, reference rails, tracing the signal path and figuring out where it stops), let me know what you find, and I’ll help as best I can.
